type Attrs = Record<string, string>;

const FONT_FAMILY = 'Ubuntu, Helvetica, Arial, sans-serif';

/**
 * Each element's `defaultAttributes` in MJML 4 (copied from the mjml-*
 * packages, v4.18.0; attributes MJML defaults to `null` are left out). MJML
 * applies them beneath `<mj-attributes>`, so an attribute nobody set still
 * means what MJML would render.
 */
export const MJML_DEFAULTS: Record<string, Attrs> = {
  'mj-body': { width: '600px' },
  'mj-section': {
    'background-repeat': 'repeat',
    'background-size': 'auto',
    'background-position': 'top center',
    direction: 'ltr',
    padding: '20px 0',
    'text-align': 'center',
    'text-padding': '4px 4px 4px 0',
  },
  'mj-wrapper': {
    'background-repeat': 'repeat',
    'background-size': 'auto',
    'background-position': 'top center',
    direction: 'ltr',
    padding: '20px 0',
    'text-align': 'center',
    'text-padding': '4px 4px 4px 0',
  },
  'mj-column': { direction: 'ltr', 'vertical-align': 'top' },
  'mj-text': {
    align: 'left',
    color: '#000000',
    'font-family': FONT_FAMILY,
    'font-size': '13px',
    'line-height': '1',
    padding: '10px 25px',
  },
  'mj-button': {
    align: 'center',
    'background-color': '#414141',
    border: 'none',
    'border-radius': '3px',
    color: '#ffffff',
    'font-family': FONT_FAMILY,
    'font-size': '13px',
    'font-weight': 'normal',
    'inner-padding': '10px 25px',
    'line-height': '120%',
    padding: '10px 25px',
    target: '_blank',
    'text-decoration': 'none',
    'text-transform': 'none',
    'vertical-align': 'middle',
  },
  'mj-image': {
    alt: '',
    align: 'center',
    border: '0',
    height: 'auto',
    padding: '10px 25px',
    target: '_blank',
    'font-size': '13px',
  },
  'mj-divider': {
    'border-color': '#000000',
    'border-style': 'solid',
    'border-width': '4px',
    padding: '10px 25px',
    width: '100%',
    align: 'center',
  },
  'mj-spacer': { height: '20px' },
  'mj-social': {
    align: 'center',
    'border-radius': '3px',
    color: '#333333',
    'font-family': FONT_FAMILY,
    'font-size': '13px',
    'icon-size': '20px',
    'line-height': '22px',
    mode: 'horizontal',
    padding: '10px 25px',
    'text-decoration': 'none',
  },
  'mj-social-element': {
    alt: '',
    align: 'left',
    'icon-position': 'left',
    color: '#000',
    'border-radius': '3px',
    'font-family': FONT_FAMILY,
    'font-size': '13px',
    'line-height': '1',
    padding: '4px',
    'text-padding': '4px 4px 4px 0',
    target: '_blank',
    'text-decoration': 'none',
    'vertical-align': 'middle',
  },
  'mj-hero': {
    mode: 'fixed-height',
    height: '0px',
    'background-position': 'center center',
    padding: '0px',
    'background-color': '#ffffff',
    'vertical-align': 'top',
  },
  'mj-navbar': {
    align: 'center',
    'ico-align': 'center',
    'ico-open': '&#9776;',
    'ico-close': '&#8855;',
    'ico-color': '#000000',
    'ico-font-size': '30px',
    'ico-font-family': FONT_FAMILY,
    'ico-text-transform': 'uppercase',
    'ico-padding': '10px',
    'ico-text-decoration': 'none',
    'ico-line-height': '30px',
  },
  'mj-navbar-link': {
    color: '#000000',
    'font-family': FONT_FAMILY,
    'font-size': '13px',
    'font-weight': 'normal',
    'line-height': '22px',
    padding: '15px 10px',
    target: '_blank',
    'text-decoration': 'none',
    'text-transform': 'uppercase',
  },
  'mj-table': {
    align: 'left',
    border: 'none',
    cellpadding: '0',
    cellspacing: '0',
    color: '#000000',
    'font-family': FONT_FAMILY,
    'font-size': '13px',
    'line-height': '22px',
    padding: '10px 25px',
    'table-layout': 'auto',
    width: '100%',
  },
};

/** The font family MJML's text-bearing elements default to. */
export const MJML_FONT_FAMILY = FONT_FAMILY;
